### ISSUE TITLE
ResearchKitOnFHIR 2.0 - Android FHIR Alignment

### ISSUE THREAD

**Issue by PSchmiedmayer** [StanfordBDHG/ResearchKitOnFHIR#86]
### Use Case

We aim to further align ResearchKitOnFHIR to [Android FHIR](https://github.com/google/android-fhir).

### Problem

In discussions with @vishnuravi, @pauljohanneskraft, @eldcn, and @Basler182 we identified the following elements that should be a first focus:
- Rendering questionnaires, especially different question types, grouping, and multiple pages
- QuestionnaireResponse output to the output that AndroidFHIR outputs and is specification conformant

### Solution

So I would see the following things we need to do toward a 2.0 release:
- [ ] Adapt ResearchKitOnFHIR to support groups with paging support like Android FHIR does it.
- [ ] Ensure that we support the radio button selection on ResearchKitOnFHIR
- [ ] Improve the ResearchKitOnFHIR questionnaire output to reflect the Android FHIR one including the nesting of groups, more fields added to the output, and therefore align it with the Android implementation.

### Alternatives considered

@vishnuravi Will further coordinate the elements with the Android FHIR project and will split up this issue into multiple smaller ones & adapt it as we move toward ResearchKitOnFHIR 2.0.

### Additional context

Outside input is more than encouraged; let us know if you want to support us in the process toward ResearchKitOnFHIR 2.0! 🚀

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

**Comment by vishnuravi** [comment]
## ResearchKit Framework Capabilities Analysis for ResearchKitOnFHIR 3.0

After examining the underlying ResearchKit framework architecture, here's what's actually possible versus what would require significant workarounds or is fundamentally limited by the framework design:

### **✅ FULLY SUPPORTED by ResearchKit**

**1. Dynamic Step Visibility (Better than expected!)**
- **ORKNavigableOrderedTask** supports conditional navigation via `ORKStepNavigationRule`
- **ORKPredicateStepNavigationRule** can evaluate complex conditions based on previous answers
- **Skip rules** via `ORKPredicateSkipStepNavigationRule` can conditionally omit steps
- **Implementation**: Can map FHIR `enableWhen` conditions to ResearchKit predicates

**2. Form Item Visibility (Excellent support)**
- **ORKFormItemVisibilityRule** allows dynamic show/hide of questions within forms
- **ORKPredicateFormItemVisibilityRule** supports NSPredicate-based conditional logic
- **Real-time evaluation** within form steps based on other form item answers
- **Implementation**: Can directly support FHIR conditional questions within groups

**3. Validation Framework (Strong existing support)**
- **Text validation** via `validationRegularExpression` with custom `invalidMessage`
- **Numeric constraints** via `minimum`/`maximum` properties on numeric answer formats
- **Length validation** via `maximumLength` on text answer formats
- **Step-level validation** enforced before navigation
- **Implementation**: Already well-utilized in ResearchKitOnFHIR

### **⚠️ PARTIALLY SUPPORTED - Needs Custom Implementation**

**4. Real-time Validation**
- **Current limitation**: Validation occurs on step completion, not during input
- **Possible enhancement**: Could extend form step controllers to validate on text change
- **Framework constraint**: Would need custom view controller modifications
- **Implementation**: Doable but requires ResearchKit framework extensions

**5. Expression Evaluation**
- **Framework gap**: No built-in expression evaluation engine
- **Workaround**: Can integrate external FHIRPath library with predicate system
- **Integration point**: Custom navigation rules and visibility rules can call expression evaluator
- **Implementation**: Feasible with external dependencies

### **❌ ARCHITECTURALLY LIMITED by ResearchKit**

**6. Draft Answer Management**
- **Fundamental limitation**: ResearchKit commits answers immediately on input completion
- **No draft state**: Results are created as soon as user provides input
- **Architecture**: Step-based model doesn't support "uncommitted" answer states
- **Workaround**: Would require significant framework modifications

**7. Continuous Scrolling UI**
- **Core design**: ResearchKit uses step-based navigation, not continuous forms
- **Cannot change**: This is fundamental to ResearchKit's research-optimized UX
- **Not needed**: Step-based approach is actually better for research contexts

**8. Real-time Cross-Step Dependencies**
- **Limitation**: Cannot dynamically modify earlier steps based on later answers
- **Forward-only**: Navigation rules only work forward, not backward
- **Architectural**: Step completion model prevents retroactive changes

### **Implementation Strategy for Each Gap**

#### **Expression Evaluation (HIGH PRIORITY - FEASIBLE)**
```swift
// Integrate FHIRPath with ResearchKit predicates
class FHIRPathPredicateRule: ORKPredicateFormItemVisibilityRule {
    init(fhirPathExpression: String, context: [String: Any]) {
        let predicate = FHIRPathEvaluator.toPredicate(fhirPathExpression, context)
        super.init(predicate: predicate)
    }
}
```

#### **Enhanced Navigation Rules (HIGH PRIORITY - FEASIBLE)**
```swift
// Map FHIR enableWhen to ResearchKit navigation
extension ORKNavigableOrderedTask {
    func addFHIREnableWhenRule(expression: String, targetStepId: String) {
        let rule = FHIRPathNavigationRule(expression: expression, destinationStep: targetStepId)
        setNavigationRule(rule, forTriggerStepIdentifier: currentStepId)
    }
}
```

#### **Group Hierarchy Preservation (HIGH PRIORITY - FEASIBLE)**
```swift
// Maintain group structure in results
extension ORKTaskResult {
    var hierarchicalFhirResponse: QuestionnaireResponse {
        // Reconstruct original group hierarchy instead of flattening
        return createHierarchicalResponse(from: self.results, structure: originalQuestionnaire)
    }
}
```

#### **Real-time Validation (MEDIUM PRIORITY - REQUIRES FRAMEWORK EXTENSION)**
```swift
// Extend form controllers for immediate validation
extension ORKFormStepViewController {
    func enableRealTimeValidation() {
        // Add text change observers and immediate validation feedback
        // Requires subclassing ResearchKit view controllers
    }
}
```

### **What's NOT Possible Without Major Framework Changes**

1. **Draft/Temporary Answer States** - ResearchKit's immediate commit model cannot be changed
2. **Retroactive Step Modifications** - Forward-only navigation is architectural 
3. **Android FHIR-style RecyclerView UI** - Incompatible with step-based design
4. **Real-time Calculated Fields Across Steps** - Limited by step isolation

### **Revised ResearchKitOnFHIR 3.0 Implementation Plan**

**Phase 1: High-Impact, High-Feasibility (Recommended for 3.0)**
1. ✅ **Group hierarchy preservation** in QuestionnaireResponse output
2. ✅ **FHIRPath expression evaluation** integration with existing predicate system
3. ✅ **Enhanced enableWhen support** via navigation and visibility rules
4. ✅ **Calculated expression support** for form item values

**Phase 2: Medium Impact, Requires Extensions**
5. ⚠️ **Real-time validation** via custom form step controllers
6. ⚠️ **Advanced item controls** (dropdown, autocomplete) via custom answer formats

**Phase 3: Not Recommended - Architectural Conflicts**
7. ❌ **Draft answer management** - Conflicts with ResearchKit design principles
8. ❌ **Continuous scrolling UI** - Incompatible with research UX paradigm

### **Conclusion**

ResearchKit actually provides **excellent support** for most Android FHIR capabilities through its navigation rules and form visibility systems. The main gaps are expression evaluation (solvable) and group hierarchy preservation (easily fixable).

The framework's step-based architecture is not a limitation but a **research-optimized design choice** that provides better user experience for study participants. Most "missing" capabilities can be implemented within ResearchKit's design paradigm.

**ResearchKitOnFHIR 3.0 can achieve near-complete Android FHIR alignment** with focused implementation of expression evaluation and hierarchy preservation.

*This comment was generated by SpeziVibe*

**Comment by vishnuravi** [comment]
## MAJOR CORRECTION: ResearchKitOnFHIR Navigation Rules Already Implemented!

I need to significantly correct my previous analysis. After examining the NavigationRules.swift file, ResearchKitOnFHIR **already has comprehensive FHIR navigation rules fully implemented**:

### **✅ ALREADY FULLY IMPLEMENTED in ResearchKitOnFHIR**

**Complete FHIR enableWhen Support** (NavigationRules.swift):
- **All enableWhen operators**: equal, notEqual, greaterThan, lessThan, greaterThanOrEqual, lessThanOrEqual, exists
- **All answer types**: coding, boolean, date, integer, decimal 
- **enableBehavior support**: both 'all' and 'any' logic
- **Automatic conversion**: `constructNavigationRules(for: questionnaire.flattenedItems)` called during task creation
- **Proper predicate negation**: Correctly handles FHIR enable vs ResearchKit skip logic

**This means ResearchKitOnFHIR already supports:**
1. ✅ Dynamic step visibility based on previous answers
2. ✅ Complex conditional logic with multiple conditions
3. ✅ All FHIR operators and answer types
4. ✅ AND/OR logic for multiple enableWhen conditions
5. ✅ Automatic integration during questionnaire conversion

### **Actual Remaining Gaps (Much Smaller Than Initially Assessed)**

**1. Group Hierarchy Preservation** (Only Real Gap)
- ORKTaskResult+FHIR.swift still flattens results with `flatMap`
- This is the PRIMARY alignment issue with Android FHIR

**2. Expression Evaluation** (calculatedExpression, answerExpression)
- enableWhen is fully supported, but calculated/derived fields are not
- Would need FHIRPath evaluation for dynamic value calculation

**3. Form Item Visibility Rules** (Partially Missing)
- ResearchKit supports ORKFormItemVisibilityRule for within-form conditional questions
- ResearchKitOnFHIR doesn't currently map FHIR enableWhen to form item visibility
- Only implements step-level skipping, not form item-level hiding

### **Revised Assessment: ResearchKitOnFHIR is Nearly Feature-Complete**

**Already Has Full Parity With Android FHIR:**
- ✅ All FHIR question types and validation
- ✅ Complete enableWhen conditional logic
- ✅ Complex navigation rules and skip logic
- ✅ FHIR metadata in QuestionnaireResponse
- ✅ Comprehensive answer format support

**Actual Work Needed for 3.0 (Minimal Scope):**
1. **Fix group hierarchy in QuestionnaireResponse** (ORKTaskResult+FHIR.swift:23)
2. **Add calculatedExpression support** (for derived values)
3. **Map enableWhen to form item visibility** (for intra-form conditional questions)

### **Implementation Priority for True Android FHIR Alignment**

**High Priority (Core Alignment)**:
1. Preserve group nesting in QuestionnaireResponse output
2. Add form item visibility rules for enableWhen within groups

**Medium Priority (Advanced Features)**:
3. FHIRPath evaluation for calculatedExpression/answerExpression

**Low Priority (Nice to Have)**:
4. Real-time validation enhancements

### **Conclusion - MAJOR REVISION**

ResearchKitOnFHIR is **much more feature-complete** than initially assessed. It already has comprehensive FHIR enableWhen support that matches Android FHIR capabilities. The main remaining work is:

1. **Group hierarchy preservation** (simple fix)
2. **Form-level conditional questions** (moderate effort)
3. **Expression evaluation** (advanced feature)

The questionnaire handling is already **very well aligned** between the two platforms. ResearchKitOnFHIR 3.0 can achieve complete Android FHIR parity with minimal additional work.

*This comment was generated by SpeziVibe*

**Comment by vishnuravi** [comment]
You're absolutely right. Here are the alignment gaps between the two platforms:

## **Alignment Gaps Between ResearchKitOnFHIR and Android FHIR:**

1. **QuestionnaireResponse structure** - ResearchKitOnFHIR flattens group hierarchy, Android FHIR maintains nested structure

2. **FHIRPath expression scope** - ResearchKitOnFHIR supports only date expressions, Android FHIR supports calculatedExpression, answerExpression, constraint validation

3. **Conditional question display approach** - ResearchKitOnFHIR uses step-level navigation rules, Android FHIR uses form-level show/hide within continuous UI

4. **Validation timing** - ResearchKitOnFHIR validates on step completion, Android FHIR validates during input

5. **Answer state management** - ResearchKitOnFHIR uses immediate commit, Android FHIR uses draft state persistence

## **What You Can Implement to Align WITHOUT Changing ResearchKit:**

### **✅ Direct Alignment Possible:**
1. **QuestionnaireResponse structure** - Modify ORKTaskResult+FHIR.swift to match Android FHIR's nested hierarchy
2. **Form item conditional display** - Use ResearchKit's ORKPredicateFormItemVisibilityRule to match Android FHIR's within-form conditional questions
3. **FHIRPath expression support** - Extend existing FHIRPathExpression engine to match Android FHIR's calculatedExpression and constraint capabilities

### **⚠️ Partial Alignment Possible:**
4. **Advanced item controls** - Add dropdown/autocomplete formats to match Android FHIR's UI variety
5. **Enhanced validation** - Use expanded FHIRPath for constraint expressions to match Android FHIR's validation scope

### **❌ Architectural Differences (Cannot Align):**
6. **Real-time validation timing** - ResearchKit's step-completion model vs Android FHIR's immediate feedback
7. **Answer state approach** - ResearchKit's immediate commit vs Android FHIR's draft persistence
8. **UI navigation paradigm** - ResearchKit's step-based vs Android FHIR's continuous scrolling

Items 1-3 would achieve strong alignment while respecting each platform's architectural strengths.

**Comment by vishnuravi** [comment]
## Implementation Details for Top 3 Alignment Items

### **1. QuestionnaireResponse Structure - Preserve Group Hierarchy**

**Current Problem**: ORKTaskResult+FHIR.swift:23 uses `flatMap` which flattens all results into a single array, losing the original group nesting.

**Solution Approach**:
- Modify the `fhirResponse` property to reconstruct the original Questionnaire item hierarchy
- Instead of flattening all results, walk through the original Questionnaire structure and match ORKStepResults to their corresponding groups
- For ORKFormStep results, map the individual ORKFormItem results back to their parent group structure
- Maintain the nested QuestionnaireResponse.item structure that mirrors the original Questionnaire.item hierarchy

**Key Changes**:
- Replace the `flatMap` approach with a recursive structure-preserving algorithm
- Use the original Questionnaire structure as a template to rebuild the response hierarchy
- Handle both individual question steps and group form steps appropriately

### **2. Form Item Conditional Display - Within-Group enableWhen**

**Current Limitation**: ResearchKitOnFHIR only implements step-level enableWhen via navigation rules. Questions within a group (ORKFormStep) don't have conditional visibility based on other questions in the same group.

**Solution Approach**:
- Extend the NavigationRules.swift logic to also create ORKPredicateFormItemVisibilityRule instances
- When processing enableWhen conditions, check if both the trigger question and target question are within the same group
- If they are in the same group, create form item visibility rules instead of (or in addition to) step navigation rules
- Use ResearchKit's existing ORKPredicateFormItemVisibilityRule system to show/hide questions within forms

**Implementation Steps**:
- Modify `constructNavigationRules` to also handle intra-group enableWhen conditions
- Create a new method to identify when enableWhen conditions should become form item visibility rules
- Map FHIR enableWhen predicates to ORKPredicateFormItemVisibilityRule instances
- Assign these visibility rules to the appropriate ORKFormItem objects

### **3. FHIRPath Expression Support - Beyond Date Expressions**

**Current Limitation**: The existing FHIRPathExpression engine is only used for minDate/maxDate expressions. Android FHIR uses FHIRPath for calculatedExpression, answerExpression, and constraint validation.

**Solution Approach**:
- Extend the existing FHIRPathParser implementation to support more FHIR extensions
- Add support for `calculatedExpression` extensions on QuestionnaireItems
- Implement `answerExpression` evaluation for derived/calculated values
- Add constraint validation using FHIRPath expressions
- Create a context evaluation system that provides access to previous answers for expression evaluation

**Implementation Areas**:
- **Calculated Values**: When a QuestionnaireItem has a calculatedExpression, evaluate it using previous answers and auto-populate the field
- **Answer Expressions**: Support expressions that derive values from other answers
- **Constraint Validation**: Use FHIRPath expressions in custom validation rules beyond the current regex support
- **Variable Support**: Implement variable scoping similar to Android FHIR (%questionnaire, %qItem, etc.)

**Technical Considerations**:
- Need to establish an evaluation context with access to current QuestionnaireResponse state
- Handle expression dependencies and evaluation order
- Integrate with ResearchKit's existing answer format and validation systems
- Ensure expressions are re-evaluated when dependent answers change (within the constraints of ResearchKit's step-based model)
